### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[3419,0] = 7126 is not in [0, 7125) 	 [[{{node linear0sparse_emb_tail/embedding_lookup}}]]

### ISSUE THREAD

**Issue by suibian1213** [zhangjing9965/KGCN_NFM#1]
你好，我在使用源码里提供的数据集运行KGCN_NFM.py文件时，遇到以下问题：
Traceback (most recent call last):
  File "/Volumes/Macintosh HD - Data/python/KGCN_NFM/KGCN_NFM.py", line 201, in <module>
    cross_validation(10, np.array(DDI))
  File "/Volumes/Macintosh HD - Data/python/KGCN_NFM/KGCN_NFM.py", line 170, in cross_validation
    train_log = train(100, 200, True, 5, train_data, test_data,False)
  File "/Volumes/Macintosh HD - Data/python/KGCN_NFM/KGCN_NFM.py", line 145, in train
    train_log = train_nfm(feature_columns, train_model_input, train_label, test_model_input, test_label, patience)
  File "/Volumes/Macintosh HD - Data/python/KGCN_NFM/KGCN_NFM.py", line 58, in train_nfm
    callbacks=[es]
  File "/Users/suibian/opt/anaconda3/envs/KGCN_NFM/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 880, in fit
    validation_steps=validation_steps)
  File "/Users/suibian/opt/anaconda3/envs/KGCN_NFM/lib/python3.7/site-packages/tensorflow/python/keras/engine/training_arrays.py", line 329, in model_iteration
    batch_outs = f(ins_batch)
  File "/Users/suibian/opt/anaconda3/envs/KGCN_NFM/lib/python3.7/site-packages/tensorflow/python/keras/backend.py", line 3076, in __call__
    run_metadata=self.run_metadata)
  File "/Users/suibian/opt/anaconda3/envs/KGCN_NFM/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1439, in __call__
    run_metadata_ptr)
  File "/Users/suibian/opt/anaconda3/envs/KGCN_NFM/lib/python3.7/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[3419,0] = 7126 is not in [0, 7125)
	 [[{{node linear0sparse_emb_tail/embedding_lookup}}]]

我在尝试解决后发现问题并没有得到解决，请问你知道我需要怎么修改吗？（不知本仓库是否还需要更新？）
另外，我在你发表的论文中看到你们同样使用了KGE_NFM作为baseline，我在复现这个模型时也有一点小疑问，不知你方不方便我向您请教。

**Comment by shismmm** [comment]
解决了吗  还有 这个代码该咋用luo's dataset

**Comment by shisumengq** [comment]
求代码  呜呜呜
